_core:
  default_config_hash: 7LkiviGITIpniIOOIzpuxR7r4XzqqYN_cwu0fb0kx1M
content_access_roles_gids:
  anonymous: 1
  authenticated: 2
  administrator: 3
  junior: 4
  middle: 5
  senior: 6
  pm: 7
  shief_pm: 8
  teamlead: 9
  seo: 10
  client: 11
